/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datos;

import java.awt.MouseInfo;
import java.awt.Point;

import Modelos.MAlmacen;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import IUModel.tablaAlmacen;

/**
 *
 * @author victo
 */
public class Buscar extends javax.swing.JFrame {

    int x, y;
    ArrayList<Float> score;
    tablaAlmacen ta;
    ArrayList<MAlmacen> li;
    String t;


    public Buscar(String t) {
        initComponents();
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                setVisible(false);
            }
        });
        this.t = t;
        setModeloTabla();
    }

    private void setModeloTabla() {
        score = new ArrayList();
        ta = new tablaAlmacen();
        li = (ArrayList<MAlmacen>) getli().clone();
        ta.setalmacen((List<MAlmacen>) li.clone());
        this.jTable1.setModel(ta);
        this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(250);
        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(1500);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
        this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(150);

    }

    public ArrayList<MAlmacen> getli() {
        ArrayList<MAlmacen> al;
        al = new ArrayList();
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            try (
                    Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/jhondee", "root", "1234")) {
                PreparedStatement s = conexion.prepareStatement("SELECT `almacen`.`codigo`,    `almacen`.`descripcion`,    `almacen`.`cantidad`,`almacen`.`monto`,    `almacen`.`minimo`, "
                        + "MATCH(descripcion) AGAINST (\"" + t + "\") as Score "
                        + "FROM almacen order by Score desc");
                ResultSet rs = s.executeQuery();
                // Se recorre el ResultSet, mostrando por pantalla los resultados.
                while (rs.next()) {
                    al.add(new MAlmacen(rs.getInt("codigo"), rs.getString("descripcion"), rs.getFloat("cantidad"), rs.getFloat("monto"), rs.getFloat("minimo")));
                    score.add(rs.getFloat("Score"));
                }
                // Se cierra la conexión con la base de datos.
            }
        } catch (SQLException e) {
        }
        return al;
    }

    public ArrayList<MAlmacen> filtro(ArrayList<MAlmacen> a) {

        for (int i = 0; i < score.size(); i++) {
            if (0 == score.get(i)) {
                score.remove(i);
            }
        }
        return a;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
