/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Datos;

import Modelos.OpAux;
import java.awt.MouseInfo;
import java.awt.Point;
import IUModel.tablaProducto;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author victo
 */
public final class Registro extends javax.swing.JFrame {

    int x, y;
    int Registro;
    tablaProducto tf;
    String Tabla;

    public Registro() {
        initComponents();
    }

    public Registro(int registro, String tabla) {
        Registro = registro;
        Tabla = tabla;
        initComponents();
        this.setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                setVisible(false);
            }
        });
        getdatos();
        ArrayList<OpAux> al;
        tf = new tablaProducto();
        al = (ArrayList<OpAux>) getpro().clone();
        tf.setalmacen((List<OpAux>) al.clone());
        Producto.setModel(tf);
        this.Producto.getColumnModel().getColumn(0).setPreferredWidth(200);
        this.Producto.getColumnModel().getColumn(1).setPreferredWidth(1500);
        this.Producto.getColumnModel().getColumn(2).setPreferredWidth(200);
        this.Producto.getColumnModel().getColumn(3).setPreferredWidth(200);
        this.Producto.getColumnModel().getColumn(4).setPreferredWidth(400);
        float p = 0;
        for (OpAux i : al) {
            p = (i.getCant() * i.getMonto());
        }
        Total.setText("Total: " + p);

    }

    public void getdatos() {
        String  d = null;
        String  r = null;
        java.util.Date f = new java.util.Date();
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            try (
                    Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/jhondee", "root", "1234")) {
                PreparedStatement s = conexion.prepareStatement("select  sql_cache `registro`.id,`registro`.descripcion,`registro`.fecha"
                        + " from `registro` inner join `" + Tabla
                        + "` on `" + Tabla + "`.registro = `registro`.id "
                        + "where `" + Tabla + "`.estatus = 'a' and "
                        + "`registro`.id = " + Registro
                        + " ORDER BY `registro`.fecha desc");
                ResultSet rs = s.executeQuery();
                // Se recorre el ResultSet, mostrando por pantalla los resultados.
                rs.next();
                f = rs.getDate("fecha");
                d = rs.getString("descripcion");
                r = "Registro N:" + rs.getInt("id");
                // Se cierra la conexión con la base de datos.
            }
        } catch (SQLException e) {
        }
        Fecha.setText("Fecha: " + f.toString());
        Descripcion.setText(d);
        registro.setText(r);
    }

    public ArrayList<OpAux> getpro() {
        ArrayList<OpAux> al;
        al = new ArrayList();
        try {
            DriverManager.registerDriver(new org.gjt.mm.mysql.Driver());
            try (
                    Connection conexion = DriverManager.getConnection("jdbc:mysql://localhost/jhondee", "root", "1234")) {
                PreparedStatement s = conexion.prepareStatement("SELECT `auxop`.`codalmacen`,`auxop`.`cantidad`,`auxop`.`monto`,`almacen`.`descripcion` "
                        + "FROM `jhondee`.`auxop` inner join `almacen` on  `auxop`.`codalmacen`=`almacen`.`codigo` "
                        + "where `auxop`.`nregistro`=" + Registro);
                ResultSet rs = s.executeQuery();
                // Se recorre el ResultSet, mostrando por pantalla los resultados.
                while (rs.next()) {
                    al.add(new OpAux(rs.getInt("codalmacen"), rs.getString("descripcion"), rs.getFloat("monto"), rs.getFloat("cantidad")));
                }
                // Se cierra la conexión con la base de datos.
            }
        } catch (SQLException e) {
        }
        return al;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        registro = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Producto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Descripcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(Descripcion);

        Fecha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        registro.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        Producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Producto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Fecha;
    private javax.swing.JTable Producto;
    private javax.swing.JLabel Total;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel registro;
    // End of variables declaration//GEN-END:variables
}
